language: go
go:
  - 1.13.x
  - tip
os:
  - linux
  - windows
  - darwin
  - freebsd
  - osx
  - netbsd
script:
  - test -z "$(go get -a)"
  - test -z "$(gofmt -l ./)"
  - test -z "$(go vet -v ./...)"
  - go test ./...
  - go build
