language: go
go:
  - 1.13.x
  - master
os:
  - linux
  - windows
  - darwin
  - freebsd
  - osx
env:
  global:
  - TRAVIS_GO_VERSION="$(cat .go-version)"
script:
  - test -z "$(go get -a)"
  - test -z "$(go vet -v ./...)"
  - go test ./...
  - go build
